baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Counterpart Cash Association (CCA)"
publishDir              = "docs"
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/"
    homepage            = "main"                        # What to call

# Metadata
    description         = "XCPC - Counterparty protocol for Bitcoin (Cash)" # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "images/twitter/cp.png"       # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/#features"
    text = "features"